# Bayes 

$$
p(c_i / x) = \frac{p(x/c_i) p(c_i)}{p(x)}
$$

## SUM RULE

$$
p(x) = \sum_x p(x,y)
$$

## Product RULE

$$
p(x,y) = p(y/x)p(x)
$$



In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Data

Telefonunuzda sipariş verebileceğiniz iki uygulama olduğunu varsayalım. Bu iki rakip uygulamayı kullanıp sipariş verdiğinizi düşünelim. Bu siparişler yemek siparişi olabilir ya da farklı bir kategoride olabilir.

Data'nız aşağıdaki birikmiş olsun.


In [2]:
uyg = [0]*10 + [1]*30
yemek = [0]*8 + [1]*2 + [0]*5 + [1]*25

data = pd.DataFrame.from_dict({"uygulama": uyg, "yemek":yemek})

In [3]:
data

uygulama  yemek
0          0      0
1          0      0
2          0      0
3          0      0
4          0      0
5          0      0
6          0      0
7          0      0
8          0      1
9          0      1
10         1      0
11         1      0
12         1      0
13         1      0
14         1      0
15         1      1
16         1      1
17         1      1
18         1      1
19         1      1
20         1      1
21         1      1
22         1      1
23         1      1
24         1      1
25         1      1
26         1      1
27         1      1
28         1      1
29         1      1
30         1      1
31         1      1
32         1      1
33         1      1
34         1      1
35         1      1
36         1      1
37         1      1
38         1      1
39         1      1

## Get Joint Probabilies

In [4]:
data[data['uygulama'] == 0]

uygulama  yemek
0         0      0
1         0      0
2         0      0
3         0      0
4         0      0
5         0      0
6         0      0
7         0      0
8         0      1
9         0      1

In [5]:
v00 = np.sum(data[data['uygulama'] == 0]['yemek'] == 0)
v00

8

In [6]:
v01 = np.sum(data[data['uygulama'] == 0]['yemek'] == 1)
v01

2

In [7]:
v10 = np.sum(data[data['uygulama'] == 1]['yemek'] == 0)
v10

5

In [8]:
v11 = np.sum(data[data['uygulama'] == 1]['yemek'] == 1)
v11

25

In [9]:
N = len(data)
N

40

## Create Count Table

In [10]:
table = np.array([[v00, v01],
                  [v10, v11]])
table

array([[ 8,  2],
       [ 5, 25]])

In [11]:
table[0,:]

array([8, 2])

In [15]:
# p(Yemek = 1)
p_yemek_1 = table[:, 1].sum()/N
p_yemek_1

0.675

In [16]:
# p(Uygulama = 1)
p_uygulama_1 = table[1, :].sum()/N
p_uygulama_1

0.75

In [17]:
# p(Yemek = 1/Uygulama = 1)
p_yemek_1_kosul_uygulama_1 = table[1, 1]/table[1, :].sum()
p_yemek_1_kosul_uygulama_1

0.8333333333333334

In [18]:
25/30

0.8333333333333334

In [20]:
# p(Uygulama = 1/Yemek = 1)
p_uygulama_1_kosul_yemek_1 = table[1, 1]/table[:, 1].sum()
p_uygulama_1_kosul_yemek_1

0.9259259259259259

In [21]:
25/27

0.9259259259259259

## Product Rule
$$
p(x,y) = p(y/x)p(x)
$$



In [22]:
# p(Uygulama = 1 ve Yemek = 1) = p(Uygulama = 1/Yemek = 1) * p(Yemek = 1)
p_uygulama_1_ve_yemek_1 = p_uygulama_1_kosul_yemek_1 * p_yemek_1
p_uygulama_1_ve_yemek_1

0.625

In [23]:
# p(Uygulama = 1 ve Yemek = 1) = p(Yemek = 1/Uygulama = 1) * p(Uygulama = 1)
p_uygulama_1_ve_yemek_1 = p_yemek_1_kosul_uygulama_1 * p_uygulama_1
p_uygulama_1_ve_yemek_1

0.625

In [24]:
# p(Yemek = 1/Uygulama = 1) * p(Uygulama = 1)
(25/30) * (30 /40) 

0.625

In [25]:
# p(Uygulama = 1/Yemek = 1) * p(Yemek = 1)
(25/27) * (27 /40) 

0.625

## SUM RULE

$$
p(x) = \sum_x p(x,y)
$$

In [27]:
# p(Uygulama = 1 ve Yemek = 1) 
p_uygulama_1_ve_yemek_1

0.625

In [29]:
table[1,1]/N

0.625

In [30]:
# p(Uygulama = 1 ve Yemek = 0) 
p_uygulama_1_ve_yemek_0  = table[1,0]/N
p_uygulama_1_ve_yemek_0

0.125

In [31]:
# p(Uygulama = 1)
# p(Uygulama = 1 ve Yemek = 1) + p(Uygulama = 1 ve Yemek = 0)
p_uygulama_1_ve_yemek_1 + p_uygulama_1_ve_yemek_0

0.75

In [32]:
table[1,:]

array([ 5, 25])

In [33]:
table[1,:].sum()/N

0.75