In [1]:
import re
import time
import numpy as np
import pandas as pd
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
start = time.time()

path = '/Users/uzaycetin/Documents/data/'
word_vectors = KeyedVectors.load_word2vec_format(path + 'trmodel', binary=True)


print("total time: ", time.time() - start)

total time:  4.486207008361816


In [4]:
word_vectors['galatasaray'].shape

(400,)

In [5]:
word_vectors.most_similar(positive=["dolar"])

[('dolarlık', 0.7788169384002686),
 ('sterlin', 0.7293490767478943),
 ('doları', 0.6988206505775452),
 ('dolara', 0.6725307703018188),
 ('sterlinlik', 0.6674367189407349),
 ('lira', 0.6478815674781799),
 ('doların', 0.6460679769515991),
 ('dolarla', 0.6405638456344604),
 ('liralık', 0.6309320330619812),
 ('avroluk', 0.6282921433448792)]

In [6]:
word_vectors.most_similar(positive=["erkek","kral"],negative=["kadın"])

[('kralı', 0.4646470248699188),
 ('prens', 0.4489177167415619),
 ('kralın', 0.4305398464202881),
 ('veliaht', 0.4213297665119171),
 ('imparator', 0.41870418190956116),
 ('tahtı', 0.41265252232551575),
 ('hükümdar', 0.3918786942958832),
 ('baudouin', 0.3889254927635193),
 ('kralların', 0.38700488209724426),
 ('dükü', 0.3815844655036926)]

In [7]:
v1 = word_vectors['elma'].reshape(1,400)
v2 = word_vectors['portakal'].reshape(1,400)
v3 = word_vectors['koltuk'].reshape(1,400)

In [8]:
cosine_similarity(v1, v2)

array([[0.49386394]], dtype=float32)

In [9]:
cosine_similarity(v1, v3)

array([[0.16753678]], dtype=float32)

In [10]:
cumle1 = 'ben nasıl büyük adam olacağım'

soz1 = 'klavye'
soz2 = 'gez toz eğlen'
soz3 = 'ulu yüce'

In [11]:
vc = np.zeros((1, 400))
kelimeler = cumle1.split()
for v in kelimeler:
    vc += word_vectors[v].reshape(1,400)
vc /= len(kelimeler) 


In [12]:
kelime = 'elmalardaki'
try:
    print(word_vectors[kelime].reshape(1,400))
except:
    print('bu kelimenin vektoru yok', kelime)

bu kelimenin vektoru yok elmalardaki


In [13]:
np.zeros((1, 4))

array([[0., 0., 0., 0.]])

In [14]:
def vectorize(cumle):
    kelimeler = cumle.split()
    vc = np.zeros((1, 400))
    n = 0
    for v in kelimeler:
        try:
            vc += word_vectors[v].reshape(1,400)
            n +=1
        except:
            continue
    vc /= n 
    return vc

In [15]:
cumle1 = 'ben nasıl büyük adam olacağım'

soz1 = 'klavye'
soz2 = 'sen gez toz eğlen, iyiyim'
soz3 = 'yücelik doğuştan gelir'

In [16]:
v_cumle1 = vectorize(cumle1)

v_soz1 = vectorize(soz1)
v_soz2 = vectorize(soz2)
v_soz3 = vectorize(soz3)

In [17]:
cosine_similarity(v_cumle1, v_soz1)

array([[0.0443544]])

In [18]:
cosine_similarity(v_cumle1, v_soz2)

array([[0.40779009]])

In [19]:
cosine_similarity(v_cumle1, v_soz3)

array([[0.17640002]])

# Yasam Kocum v2

In [20]:
Hayat = """
Olumlu düşünen, bütün olası dünyaların en iyisinde yaşadığımızı söyler ve olumsuz düşünen, bunun gerçek olmasından korkar. James Cabell

Bu dünyaya gelmenin sadece tek bir yolu vardır, terk etmenin ise çok fazla yolu. Donald Harington

Birisinin ‘Hayat zor.’ diye yakındığını duyduğumda, her zaman, ‘Neye kıyasla?’ diye sormayı isterim. Sidney Harris

Mutsuz olmamamız gerekir. Kimsenin hayatla bir kontratı yok. DavidHeath

Hayatını kazanırken yaşamasını bilmeyen bir adam, servetini kazanmadan öncesine göre daha fakirdir. Josiah Holland

Yarının ne olacağını sormaktan vazgeç. Her gün, sana verilen bir hazinedir. Eline geçtikçe değerlendir. Horace

Hayatınızı yaşamanın en iyi yolu, sizden sonra da kalıcı olacak şeyler için harcamaktır. William James

Biz Japonlar, küçük zevklerden hoşlanırız, israftan değil. Daha fazlasını karşılayabilirse de, insanın basit bir yaşam tarzı olması kanısındayım. Massaru Ibuka

Benim sanatım ve mesleğim yaşamaktır. Montaigne

Hayat, çikolata ile dolu bir kutu gibidir. Ne çıkacağını asla bilemezsiniz. Forrest Gump Filmi

Hayat, büyük bir sürprizdir. Ölümün neden daha büyük bir sürpriz olması gerektiğini anlayamıyorum. Vladimir Nabokov
"""


Sevgi = """
Karım,  benim  ‘Seni seviyorum.’  dememi binlerce kez duydu ama, hiçbir zaman ‘Üzgünüm.’ dediğimi duymadı. Bruce Willis

Büyüklerine saygı, küçüklerine şevkat göstermeyenler, bizden değildir. Hz, Muhammed

Sevip de kaybetmek, sevmemiş olmaktan daha iyidir. Seneca

Sevgiyle düşünün, sevgiyle konuşun, sevgiyle davranın. Her ihtiyaç karşılanacaktır. James Ailen

Sevgi, insanı birliğe, bencillik ise yalnızlığa götürür. Schiller

Sevdiği kadını ve sevdiği işi bulan bir erkek, yeryüzünde cenneti bulmuş demektir. Helen Rowland

Kızgınlık, kırgınlık ya da acıya tutunmayın. Enerjinizi çalarlar ve sizi sevmekten alıkoyarlar. Leo Buscaglia

Herkes temel bir şeyi unutuyor; insanlar sizi, siz onları sevmeden sevmeyecekler. Pat Carroll

Sevgi, dünyadaki yaşamın aktığı nehirdir. Henry Beecher

Sevmeden verebilirsiniz ama, vermeden sevemezsiniz. Amy Carmichael

"""

Gayret = """
Dileyin verilecektir; arayın bulacaksınız; kapıyı çalın size açılacaktır.    Hz.İsa (a.s.)

Damlayan su, mermeri, yürüyen de dağları deler. Ovidius

Hazine, eziyet çekene gözükür.    Hz. Mevlâna

Beklenen gün gelecekse, çekilen çile kutsaldır.V. Hugo

Yarınlar yorgun ve bezgin kimseler değil, rahatını terk edebilen gayretli insanlara aittir. Cicero

Emek olmadan, yemek olmaz.    Atasözü

Kötülüğün hakim olmaması için tek şart, iyilerin gayret göstermeleridir. Kelâmı Kibar

İnsan bir şeyi çok ciddi olarak arzu etmeye görsün; hiçbir şey erişilemeyecek kadar yükseklerde değildir. H. Andersen

Ümitsizlik ve korkaklık, çalışma azminden yoksun insanlara göredir.  A. Mourois

Bir çığlık, bir çığ meydana getirir.  Soljenitsin

Kıramıyacağm zinciri, hiç olmazsa kemir. C. Şehabettin

Basit bir insanın elinden geleni yapması; bilgili ve zeki bir insanın tembelliğinden çok daha değerlidir.

Taşı delen, suyun kuvveti değil; dalgaların sürekliliğidir.

Damlayan su, taşı deler. Ovidius
"""

Umut = """
Başlangıçta fazla umut ederiz ama, sonrasında yeteri kadar değil. Joesph Roux

Hayatta umutsuz durumlar yoktur,  sadece umutsuzluk besleyen insanlar vardır. Booth

Şafaktan önce her yer karanlıktır. Katherine Mansfield

Umut, gözle görülemeyeni görür, elle tutulamayanı hisseder ve imkansızı başarır. Anonim

Büyük umutlar, büyük adamlar yaratır. Thomas Fuller

Umut, fakirin ekmeğidir. Thales Miletus

Kazanmayı umut etmeyen, daha baştan kaybetmiştir. Jose Olmedo

Umut etmeyen, hiçbir zaman umutsuzluğa kapılmaz. George Bernard Shaw

Hiçbir kış, sonsuza kadar sürmez. Hal Borland

Umut, şüphe etmek daha kolayken, inanmaya devam etmektir. Anonim

Umut, mutluluktan alınmış bir miktar borçtur. Joseph İoubert
"""

Idare = """
Çok söyleyen değil, çok iş yapan yöneticiye muhtaçsınız. Hz. Ömer (r.a.)

Sevginin kurduğu devleti, adalet devam ettirir. Farabi

Her memleketin hakettiği bir hükümeti vardır. J. Maistere

Hükümetlerin en kötüsü, suçsuzu korkutandır.

Kendinizi yönetirken kafanızı, başkalarını yönetirken kalbinizi kullanın.

Evi ev eden avrat, yurdu şen eden devlet. Atasözü

Mal cimrilerde, silah korkanlarda, idare de zayıflarda olursa, işler bozulur. Hz. Ebubekir

İnsanlar üç sınıftır: İdareciler, din alimleri ve halk. İdareciler bozulunca, geçim; alimler bozulunca, din; halk bozulunca da hak bozulur. Ebu Bekir Verrak

Kendini yönet, dünyayı yönetecek gücü bulabilirsin. Plato

Kötü idarecilerin başarısı, halkın ıstırabıdır.

Bir memlekette ayaklar baş olursa, başlar ayaklar altında mahvolur.

"""

In [21]:
categories = [Hayat,Sevgi,Gayret,Umut,Idare]
categories_name = ["hayat", "sevgi", "gayret", "umut", "idare"]

In [22]:

for i in range(len(categories)):
    categories[i] = categories[i].split("\n")

In [23]:

df = pd.DataFrame(columns=['sentence','category'])

In [24]:
for i in range(len(categories_name)):
    for k in range(len(categories[i])):
        df = df.append({'sentence': categories[i][k], 'category': categories_name[i]}, ignore_index=True)
    
    df = df[df['sentence']!=""]
    df.reset_index(drop=True, inplace=True)

In [25]:
df

sentence category
0   Olumlu düşünen, bütün olası dünyaların en iyis...    hayat
1   Bu dünyaya gelmenin sadece tek bir yolu vardır...    hayat
2   Birisinin ‘Hayat zor.’ diye yakındığını duyduğ...    hayat
3   Mutsuz olmamamız gerekir. Kimsenin hayatla bir...    hayat
4   Hayatını kazanırken yaşamasını bilmeyen bir ad...    hayat
5   Yarının ne olacağını sormaktan vazgeç. Her gün...    hayat
6   Hayatınızı yaşamanın en iyi yolu, sizden sonra...    hayat
7   Biz Japonlar, küçük zevklerden hoşlanırız, isr...    hayat
8     Benim sanatım ve mesleğim yaşamaktır. Montaigne    hayat
9   Hayat, çikolata ile dolu bir kutu gibidir. Ne ...    hayat
10  Hayat, büyük bir sürprizdir. Ölümün neden daha...    hayat
11  Karım,  benim  ‘Seni seviyorum.’  dememi binle...    sevgi
12  Büyüklerine saygı, küçüklerine şevkat gösterme...    sevgi
13  Sevip de kaybetmek, sevmemiş olmaktan daha iyi...    sevgi
14  Sevgiyle düşünün, sevgiyle konuşun, sevgiyle d...    sevgi
15  Sevgi, insanı birliğe, bencillik ise yalnızlığ...    sevgi
16  Sevdiği kadını ve sevdiği işi bulan bir erkek,...    sevgi
17  Kızgınlık, kırgınlık ya da acıya tutunmayın. E...    sevgi
18  Herkes temel bir şeyi unutuyor; insanlar sizi,...    sevgi
19  Sevgi, dünyadaki yaşamın aktığı nehirdir. Henr...    sevgi
20  Sevmeden verebilirsiniz ama, vermeden sevemezs...    sevgi
21  Dileyin verilecektir; arayın bulacaksınız; kap...   gayret
22  Damlayan su, mermeri, yürüyen de dağları deler...   gayret
23      Hazine, eziyet çekene gözükür.    Hz. Mevlâna   gayret
24  Beklenen gün gelecekse, çekilen çile kutsaldır...   gayret
25  Yarınlar yorgun ve bezgin kimseler değil, raha...   gayret
26              Emek olmadan, yemek olmaz.    Atasözü   gayret
27  Kötülüğün hakim olmaması için tek şart, iyiler...   gayret
28  İnsan bir şeyi çok ciddi olarak arzu etmeye gö...   gayret
29  Ümitsizlik ve korkaklık, çalışma azminden yoks...   gayret
30  Bir çığlık, bir çığ meydana getirir.  Soljenitsin   gayret
31  Kıramıyacağm zinciri, hiç olmazsa kemir. C. Şe...   gayret
32  Basit bir insanın elinden geleni yapması; bilg...   gayret
33  Taşı delen, suyun kuvveti değil; dalgaların sü...   gayret
34                   Damlayan su, taşı deler. Ovidius   gayret
35  Başlangıçta fazla umut ederiz ama, sonrasında ...     umut
36  Hayatta umutsuz durumlar yoktur,  sadece umuts...     umut
37  Şafaktan önce her yer karanlıktır. Katherine M...     umut
38  Umut, gözle görülemeyeni görür, elle tutulamay...     umut
39  Büyük umutlar, büyük adamlar yaratır. Thomas F...     umut
40            Umut, fakirin ekmeğidir. Thales Miletus     umut
41  Kazanmayı umut etmeyen, daha baştan kaybetmişt...     umut
42  Umut etmeyen, hiçbir zaman umutsuzluğa kapılma...     umut
43      Hiçbir kış, sonsuza kadar sürmez. Hal Borland     umut
44  Umut, şüphe etmek daha kolayken, inanmaya deva...     umut
45  Umut, mutluluktan alınmış bir miktar borçtur. ...     umut
46  Çok söyleyen değil, çok iş yapan yöneticiye mu...    idare
47  Sevginin kurduğu devleti, adalet devam ettirir...    idare
48  Her memleketin hakettiği bir hükümeti vardır. ...    idare
49       Hükümetlerin en kötüsü, suçsuzu korkutandır.    idare
50  Kendinizi yönetirken kafanızı, başkalarını yön...    idare
51  Evi ev eden avrat, yurdu şen eden devlet. Atasözü    idare
52  Mal cimrilerde, silah korkanlarda, idare de za...    idare
53  İnsanlar üç sınıftır: İdareciler, din alimleri...    idare
54  Kendini yönet, dünyayı yönetecek gücü bulabili...    idare
55    Kötü idarecilerin başarısı, halkın ıstırabıdır.    idare
56  Bir memlekette ayaklar baş olursa, başlar ayak...    idare

In [26]:
df["cleaned_sentence"]=df['sentence'].copy()

for i in range(len(df)):
    df["cleaned_sentence"][i] = re.sub('[;!@#’‘?.,\'$]', '', df["cleaned_sentence"][i])
    df["cleaned_sentence"][i] = df["cleaned_sentence"][i].lower()

In [27]:
df

sentence category  \
0   Olumlu düşünen, bütün olası dünyaların en iyis...    hayat   
1   Bu dünyaya gelmenin sadece tek bir yolu vardır...    hayat   
2   Birisinin ‘Hayat zor.’ diye yakındığını duyduğ...    hayat   
3   Mutsuz olmamamız gerekir. Kimsenin hayatla bir...    hayat   
4   Hayatını kazanırken yaşamasını bilmeyen bir ad...    hayat   
5   Yarının ne olacağını sormaktan vazgeç. Her gün...    hayat   
6   Hayatınızı yaşamanın en iyi yolu, sizden sonra...    hayat   
7   Biz Japonlar, küçük zevklerden hoşlanırız, isr...    hayat   
8     Benim sanatım ve mesleğim yaşamaktır. Montaigne    hayat   
9   Hayat, çikolata ile dolu bir kutu gibidir. Ne ...    hayat   
10  Hayat, büyük bir sürprizdir. Ölümün neden daha...    hayat   
11  Karım,  benim  ‘Seni seviyorum.’  dememi binle...    sevgi   
12  Büyüklerine saygı, küçüklerine şevkat gösterme...    sevgi   
13  Sevip de kaybetmek, sevmemiş olmaktan daha iyi...    sevgi   
14  Sevgiyle düşünün, sevgiyle konuşun, sevgiyle d...    sevgi   
15  Sevgi, insanı birliğe, bencillik ise yalnızlığ...    sevgi   
16  Sevdiği kadını ve sevdiği işi bulan bir erkek,...    sevgi   
17  Kızgınlık, kırgınlık ya da acıya tutunmayın. E...    sevgi   
18  Herkes temel bir şeyi unutuyor; insanlar sizi,...    sevgi   
19  Sevgi, dünyadaki yaşamın aktığı nehirdir. Henr...    sevgi   
20  Sevmeden verebilirsiniz ama, vermeden sevemezs...    sevgi   
21  Dileyin verilecektir; arayın bulacaksınız; kap...   gayret   
22  Damlayan su, mermeri, yürüyen de dağları deler...   gayret   
23      Hazine, eziyet çekene gözükür.    Hz. Mevlâna   gayret   
24  Beklenen gün gelecekse, çekilen çile kutsaldır...   gayret   
25  Yarınlar yorgun ve bezgin kimseler değil, raha...   gayret   
26              Emek olmadan, yemek olmaz.    Atasözü   gayret   
27  Kötülüğün hakim olmaması için tek şart, iyiler...   gayret   
28  İnsan bir şeyi çok ciddi olarak arzu etmeye gö...   gayret   
29  Ümitsizlik ve korkaklık, çalışma azminden yoks...   gayret   
30  Bir çığlık, bir çığ meydana getirir.  Soljenitsin   gayret   
31  Kıramıyacağm zinciri, hiç olmazsa kemir. C. Şe...   gayret   
32  Basit bir insanın elinden geleni yapması; bilg...   gayret   
33  Taşı delen, suyun kuvveti değil; dalgaların sü...   gayret   
34                   Damlayan su, taşı deler. Ovidius   gayret   
35  Başlangıçta fazla umut ederiz ama, sonrasında ...     umut   
36  Hayatta umutsuz durumlar yoktur,  sadece umuts...     umut   
37  Şafaktan önce her yer karanlıktır. Katherine M...     umut   
38  Umut, gözle görülemeyeni görür, elle tutulamay...     umut   
39  Büyük umutlar, büyük adamlar yaratır. Thomas F...     umut   
40            Umut, fakirin ekmeğidir. Thales Miletus     umut   
41  Kazanmayı umut etmeyen, daha baştan kaybetmişt...     umut   
42  Umut etmeyen, hiçbir zaman umutsuzluğa kapılma...     umut   
43      Hiçbir kış, sonsuza kadar sürmez. Hal Borland     umut   
44  Umut, şüphe etmek daha kolayken, inanmaya deva...     umut   
45  Umut, mutluluktan alınmış bir miktar borçtur. ...     umut   
46  Çok söyleyen değil, çok iş yapan yöneticiye mu...    idare   
47  Sevginin kurduğu devleti, adalet devam ettirir...    idare   
48  Her memleketin hakettiği bir hükümeti vardır. ...    idare   
49       Hükümetlerin en kötüsü, suçsuzu korkutandır.    idare   
50  Kendinizi yönetirken kafanızı, başkalarını yön...    idare   
51  Evi ev eden avrat, yurdu şen eden devlet. Atasözü    idare   
52  Mal cimrilerde, silah korkanlarda, idare de za...    idare   
53  İnsanlar üç sınıftır: İdareciler, din alimleri...    idare   
54  Kendini yönet, dünyayı yönetecek gücü bulabili...    idare   
55    Kötü idarecilerin başarısı, halkın ıstırabıdır.    idare   
56  Bir memlekette ayaklar baş olursa, başlar ayak...    idare   

                                     cleaned_sentence  
0   olumlu düşünen bütün olası dünyaların en iyisi...  
1   bu dünyaya gelmenin sadece tek bir yolu vardır...  
2   birisinin hayat zor diye yakındığını duyduğu

In [28]:
df['vectors'] = df['cleaned_sentence'].apply(vectorize)

In [29]:
df

sentence category  \
0   Olumlu düşünen, bütün olası dünyaların en iyis...    hayat   
1   Bu dünyaya gelmenin sadece tek bir yolu vardır...    hayat   
2   Birisinin ‘Hayat zor.’ diye yakındığını duyduğ...    hayat   
3   Mutsuz olmamamız gerekir. Kimsenin hayatla bir...    hayat   
4   Hayatını kazanırken yaşamasını bilmeyen bir ad...    hayat   
5   Yarının ne olacağını sormaktan vazgeç. Her gün...    hayat   
6   Hayatınızı yaşamanın en iyi yolu, sizden sonra...    hayat   
7   Biz Japonlar, küçük zevklerden hoşlanırız, isr...    hayat   
8     Benim sanatım ve mesleğim yaşamaktır. Montaigne    hayat   
9   Hayat, çikolata ile dolu bir kutu gibidir. Ne ...    hayat   
10  Hayat, büyük bir sürprizdir. Ölümün neden daha...    hayat   
11  Karım,  benim  ‘Seni seviyorum.’  dememi binle...    sevgi   
12  Büyüklerine saygı, küçüklerine şevkat gösterme...    sevgi   
13  Sevip de kaybetmek, sevmemiş olmaktan daha iyi...    sevgi   
14  Sevgiyle düşünün, sevgiyle konuşun, sevgiyle d...    sevgi   
15  Sevgi, insanı birliğe, bencillik ise yalnızlığ...    sevgi   
16  Sevdiği kadını ve sevdiği işi bulan bir erkek,...    sevgi   
17  Kızgınlık, kırgınlık ya da acıya tutunmayın. E...    sevgi   
18  Herkes temel bir şeyi unutuyor; insanlar sizi,...    sevgi   
19  Sevgi, dünyadaki yaşamın aktığı nehirdir. Henr...    sevgi   
20  Sevmeden verebilirsiniz ama, vermeden sevemezs...    sevgi   
21  Dileyin verilecektir; arayın bulacaksınız; kap...   gayret   
22  Damlayan su, mermeri, yürüyen de dağları deler...   gayret   
23      Hazine, eziyet çekene gözükür.    Hz. Mevlâna   gayret   
24  Beklenen gün gelecekse, çekilen çile kutsaldır...   gayret   
25  Yarınlar yorgun ve bezgin kimseler değil, raha...   gayret   
26              Emek olmadan, yemek olmaz.    Atasözü   gayret   
27  Kötülüğün hakim olmaması için tek şart, iyiler...   gayret   
28  İnsan bir şeyi çok ciddi olarak arzu etmeye gö...   gayret   
29  Ümitsizlik ve korkaklık, çalışma azminden yoks...   gayret   
30  Bir çığlık, bir çığ meydana getirir.  Soljenitsin   gayret   
31  Kıramıyacağm zinciri, hiç olmazsa kemir. C. Şe...   gayret   
32  Basit bir insanın elinden geleni yapması; bilg...   gayret   
33  Taşı delen, suyun kuvveti değil; dalgaların sü...   gayret   
34                   Damlayan su, taşı deler. Ovidius   gayret   
35  Başlangıçta fazla umut ederiz ama, sonrasında ...     umut   
36  Hayatta umutsuz durumlar yoktur,  sadece umuts...     umut   
37  Şafaktan önce her yer karanlıktır. Katherine M...     umut   
38  Umut, gözle görülemeyeni görür, elle tutulamay...     umut   
39  Büyük umutlar, büyük adamlar yaratır. Thomas F...     umut   
40            Umut, fakirin ekmeğidir. Thales Miletus     umut   
41  Kazanmayı umut etmeyen, daha baştan kaybetmişt...     umut   
42  Umut etmeyen, hiçbir zaman umutsuzluğa kapılma...     umut   
43      Hiçbir kış, sonsuza kadar sürmez. Hal Borland     umut   
44  Umut, şüphe etmek daha kolayken, inanmaya deva...     umut   
45  Umut, mutluluktan alınmış bir miktar borçtur. ...     umut   
46  Çok söyleyen değil, çok iş yapan yöneticiye mu...    idare   
47  Sevginin kurduğu devleti, adalet devam ettirir...    idare   
48  Her memleketin hakettiği bir hükümeti vardır. ...    idare   
49       Hükümetlerin en kötüsü, suçsuzu korkutandır.    idare   
50  Kendinizi yönetirken kafanızı, başkalarını yön...    idare   
51  Evi ev eden avrat, yurdu şen eden devlet. Atasözü    idare   
52  Mal cimrilerde, silah korkanlarda, idare de za...    idare   
53  İnsanlar üç sınıftır: İdareciler, din alimleri...    idare   
54  Kendini yönet, dünyayı yönetecek gücü bulabili...    idare   
55    Kötü idarecilerin başarısı, halkın ıstırabıdır.    idare   
56  Bir memlekette ayaklar baş olursa, başlar ayak...    idare   

                                     cleaned_sentence  \
0   olumlu düşünen bütün olası dünyaların en iyisi...   
1   bu dünyaya gelmenin sadece tek bir yolu vardır...   
2   birisinin hayat zor diye yakındığını duyd

In [32]:
cvp = input("Insan hangi konuda tavsiye istersin? \n (Hayat/Sevgi/Gayret/Umut/Idare) \n \t cevap: ")
cvp = cvp.lower()


Insan hangi konuda tavsiye istersin? 
 (Hayat/Sevgi/Gayret/Umut/Idare) 
 	 cevap: çalış


In [33]:
v_cvp = vectorize(cvp)

In [34]:
cosine_similarity(v_cvp, df['vectors'][0])

array([[0.02581348]])

In [35]:
f = lambda x: cosine_similarity(v_cvp, x)[0,0]
sonuc = df['vectors'].apply(f)

In [36]:
df.iloc[sonuc.idxmax()]['sentence']

'Kendinizi yönetirken kafanızı, başkalarını yönetirken kalbinizi kullanın.'

In [37]:
cvp = input("Insan hangi konuda tavsiye istersin? \n (Hayat/Sevgi/Gayret/Umut/Idare) \n \t cevap: ")
cvp = cvp.lower()
v_cvp = vectorize(cvp)
f = lambda x: cosine_similarity(v_cvp, x)[0,0]
sonuc = df['vectors'].apply(f)
print(df.iloc[sonuc.idxmax()]['sentence'])

Insan hangi konuda tavsiye istersin? 
 (Hayat/Sevgi/Gayret/Umut/Idare) 
 	 cevap: çalış
Kendinizi yönetirken kafanızı, başkalarını yönetirken kalbinizi kullanın.


# Yapilacaklar

Turkce stopwords lerden kurtul : https://github.com/sgsinclair/trombone/blob/master/src/main/resources/org/voyanttools/trombone/keywords/stop.tr.turkish-lucene.txt

Kelime kokune in

In [38]:
url ='https://raw.githubusercontent.com/sgsinclair/trombone/master/src/main/resources/org/voyanttools/trombone/keywords/stop.tr.turkish-lucene.txt'
data = pd.read_csv(url)

In [39]:
data

# Turkish stopwords from LUCENE-559
0    # merged with the list from "Information Retri...
1    #   (http://www.users.muohio.edu/canf/papers/J...
2                                                acaba
3                                               altmış
4                                                 altı
..                                                 ...
206                                               yine
207                                              yirmi
208                                              yoksa
209                                                yüz
210                                              zaten

[211 rows x 1 columns]

In [40]:
stpwrds = set(data[2:].iloc[:, 0].values)

In [41]:
def vectorize(cumle, stpwrds):
    kelimeler = cumle.split()
    vc = np.zeros((1, 400))
    n = 0
    for v in kelimeler:
        if v in stpwrds:
            continue
        try:
            vc += word_vectors[v].reshape(1,400)
            n +=1
        except:
            continue
    vc /= n 
    return vc

In [42]:
cvp = input("Insan hangi konuda tavsiye istersin? \n (Hayat/Sevgi/Gayret/Umut/Idare) \n \t cevap: ")
cvp = cvp.lower()
v_cvp = vectorize(cvp, stpwrds)
f = lambda x: cosine_similarity(v_cvp, x)[0,0]
sonuc = df['vectors'].apply(f)
print(df.iloc[sonuc.idxmax()]['sentence'])

Insan hangi konuda tavsiye istersin? 
 (Hayat/Sevgi/Gayret/Umut/Idare) 
 	 cevap: ben nasıl büyük adam olurum
Büyük umutlar, büyük adamlar yaratır. Thomas Fuller


# Ses Tanima ile tavsiye al

In [ ]:
import speech_recognition as sr
mic = sr.Microphone()
r = sr.Recognizer()

def recognize_speech_from_mic(recognizer, microphone, firsttime = False):
    """Transcribe speech from recorded from `microphone`.

    Returns a dictionary with three keys:
    "success": a boolean indicating whether or not the API request was
               successful
    "error":   `None` if no error occured, otherwise a string containing
               an error message if the API could not be reached or
               speech was unrecognizable
    "transcription": `None` if speech could not be transcribed,
               otherwise a string containing the transcribed text
    """
    # check that recognizer and microphone arguments are appropriate type
    if not isinstance(recognizer, sr.Recognizer):
        raise TypeError("`recognizer` must be `Recognizer` instance")

    if not isinstance(microphone, sr.Microphone):
        raise TypeError("`microphone` must be `Microphone` instance")

    # adjust the recognizer sensitivity to ambient noise and record audio
    # from the microphone
    with microphone as source:
        if firsttime == True:
            recognizer.adjust_for_ambient_noise(source)
        print('recording..')
        audio = recognizer.listen(source)

    # set up the response object
    response = {
        "success": True,
        "error": None,
        "transcription": None
    }

    # try recognizing the speech in the recording
    # if a RequestError or UnknownValueError exception is caught,
    #     update the response object accordingly
    try:
        response["transcription"] = recognizer.recognize_google(audio, language='tr-tr')
    except sr.RequestError:
        # API was unreachable or unresponsive
        response["success"] = False
        response["error"] = "API unavailable"
    except sr.UnknownValueError:
        # speech was unintelligible
        response["error"] = "Unable to recognize speech"

    return response

In [ ]:
guess = recognize_speech_from_mic(r, mic)

guess['transcription']

In [ ]:
guess = recognize_speech_from_mic(r, mic)

cvp = guess['transcription'].lower()
print(cvp)
print()
v_cvp = vectorize(cvp, stpwrds)
f = lambda x: cosine_similarity(v_cvp, x)[0,0]
sonuc = df['vectors'].apply(f)
print(df.iloc[sonuc.idxmax()]['sentence'])