# Least Square Solution
![](LeastSquare.png)

In [1]:
import numpy as np

In [2]:
n, d = 1000, 5

In [3]:
X = np.random.rand(n,d)

In [4]:
y = X.mean(axis = 1)

In [5]:
y.sum()

506.5047024307777

In [6]:
XTX = np.dot(X.T, X)
XTX.shape

(5, 5)

In [7]:
XTXINV = np.linalg.inv(XTX)
XTXINV.shape

(5, 5)

In [8]:
XTY = np.dot(X.T, y)
XTY.shape

(5,)

In [9]:
w = np.dot(XTXINV, XTY)
w

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [10]:
yhat = np.dot(X, w)

In [11]:
np.sum(yhat - y)

-1.6199541708061815e-13

# Formulation - Least Square Solution

Data = Signal + Noise
$$
y = f(x) + \epsilon 
$$

Where $f(x) = Xw$

## Generate Data

In [19]:
# Generate Data
n, d = 1000000, 100
X = np.random.rand(n,d)

# Signal
    # When you take average with mean(), 
    # you give equal weight (1/d) to each feature, 
signal = X.mean(axis = 1)

# Noise
noise = np.random.rand(n,) /100

# Data
y =  signal + noise

## Solution

In [20]:
XTX = np.dot(X.T, X)
XTXINV = np.linalg.inv(XTX)
XTY = np.dot(X.T, y)
w = np.dot(XTXINV, XTY)
w

array([0.01009343, 0.01008596, 0.01010215, 0.0101094 , 0.01011016,
       0.01009838, 0.01008166, 0.0101165 , 0.01009913, 0.01009807,
       0.01010921, 0.01009757, 0.01010795, 0.01010437, 0.01009239,
       0.01010985, 0.01011204, 0.01008617, 0.01009034, 0.01009318,
       0.01009497, 0.01010498, 0.01008189, 0.01008292, 0.01011521,
       0.01009488, 0.01008972, 0.01010818, 0.0100906 , 0.01009524,
       0.01007767, 0.01009892, 0.01008767, 0.01008866, 0.01011385,
       0.01009751, 0.01011588, 0.01011224, 0.01008544, 0.01008879,
       0.01010828, 0.01010504, 0.01010744, 0.01009024, 0.01008977,
       0.01010414, 0.01010574, 0.01009128, 0.01009452, 0.01009289,
       0.01008451, 0.01010434, 0.01009222, 0.0101046 , 0.01011472,
       0.01010576, 0.01010435, 0.01009471, 0.01009821, 0.01008988,
       0.01011207, 0.01009885, 0.01011057, 0.01011299, 0.01008124,
       0.01008664, 0.01009934, 0.01009881, 0.01009843, 0.01011578,
       0.01009583, 0.01011348, 0.0100828 , 0.01009795, 0.01009

# İşe Alım Verisi

In [22]:
import numpy as np
import pandas as pd

import requests
import io


url = "https://raw.githubusercontent.com/uzay00/KaVe-Egitim/master/ARGE/Sorular/1-İseAlımRobotu/data.csv"
s = requests.get(url).content

data = pd.read_csv(io.StringIO(s.decode('utf-8')))
data

age  algorithm       gpa    social  y
0    3.576113   3.728920  0.930603  4.438372  1
1    1.829891   4.393183  3.137649  4.831307  1
2    3.981593   4.050717  3.886304  4.865860  1
3    1.734623   4.605488  2.605315  3.663224  1
4    2.759050   4.288383  1.894925  3.238931  1
..        ...        ...       ...       ... ..
995  0.756427   0.931875  2.769794  0.218749  0
996  3.344518   1.182757  2.696908  0.735196  0
997  1.812786   1.081876  2.940970  1.076683  0
998  2.316372   2.211849  4.594402  0.614308  0
999  1.845348   1.809162  3.783898  0.629247  0

[1000 rows x 5 columns]

In [23]:
idx_train = np.random.choice(1000, size = 800,replace = False)

In [24]:
idx_test = np.array(list(set(range(1000)) - set(idx_train)))

In [41]:
X_train = data.values[idx_train, :-1]
y_train = data.values[idx_train, -1]

In [42]:
X_test = data.values[idx_test, :-1]
y_test = data.values[idx_test, -1]

In [43]:
def leastsquare(X, y):
    XTX = np.dot(X.T, X)
    XTXINV = np.linalg.inv(XTX)
    XTY = np.dot(X.T, y)
    w = np.dot(XTXINV, XTY)
    return w

In [44]:
w = leastsquare(X_train, y_train)

In [46]:
w

array([-0.03027535,  0.11682794, -0.03376863,  0.12444453])

In [47]:
y_hat = np.dot(X_test,w)
y_hat.shape

(200,)

In [48]:
y_hat

array([ 0.84827993,  0.10380341,  0.23413703,  0.01382315, -0.01945005,
        0.95540057,  0.14016386, -0.09474477,  0.87466829,  0.07268193,
        0.82723253, -0.10331694, -0.02478553,  0.86779698, -0.08183577,
       -0.0120177 ,  0.08638828,  0.80164852,  0.92533897, -0.11170882,
        0.00445056,  0.9489995 ,  0.79017488, -0.0752375 , -0.10954375,
        0.23259053,  0.00792392, -0.07719663, -0.01426011,  0.18984695,
        0.92644957,  0.57398609,  0.07193158,  0.04215846, -0.0538264 ,
        0.90725067,  0.95341818,  0.92414776,  0.3523862 ,  0.97420245,
       -0.09925784,  0.03302611,  0.0124821 ,  0.24260392,  0.05453726,
        0.12807578, -0.03625106,  0.07147381,  0.22871354,  0.01637949,
        0.15346802,  0.21167992, -0.09902408,  0.22285762,  0.21910228,
       -0.15063255, -0.04980437, -0.08274074, -0.03822665,  0.15122674,
        0.04389496, -0.03889836, -0.04717826,  0.24064613,  0.33080513,
        0.18171212, -0.03338466, -0.11570362, -0.07629339,  0.00

In [49]:
y_pred = 1 * (y_hat > 0.5)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [50]:
y_test

array([1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[184,   0],
       [  1,  15]])

# Linear Regression

Model 
$$
\hat{y} = Xw
$$

Error
$$
J(w) = \frac{1}{2n} ||y - \hat{y}||_2 = \frac{1}{2n}(y - \hat{y})^T(y - \hat{y})
$$

Gradient

$$
\frac{dJ}{dw} = \frac{1}{n} X^T(y - \hat{y})
$$

![](LeastSquare-gradient.png)

In [52]:
n = X_train.shape[0]   # ornek sayisi
d = X_train.shape[1]   # oznitelik sayisi
y_train = y_train.reshape(-1,1)



alpha =  0.01
Js = []
w  = np.random.rand(d,1) # rastgele d agirlik parametre degeri

for i in range(1000):
    # ileri yayilim
    h = np.dot(X_train, w) 
    # geri yayilim
    dw = (1 / n) * np.dot(X_train.T, (h - y_train))
    # Egim Inis
    w = w - alpha * dw
    
    if i%100:
        Js.append((1 / (2 * n)) * np.sum(np.power(h - y_train,2)))
    
print("w: {}\n".format(w))

w: [[-0.03029581]
 [ 0.11484898]
 [-0.03368894]
 [ 0.12633072]]



In [53]:
y_hat = np.dot(X_test,w)
y_hat.shape

(200, 1)

In [54]:
y_pred = 1 * (y_hat > 0.5)
y_pred = y_pred.flatten()
y_pred.shape

(200,)

In [55]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[184,   0],
       [  1,  15]])