In [1]:
import numpy as np

a = np.array([2,4,6,8])
b = np.array([1,3,5,7])

In [2]:
mu_a = np.mean(a)
mu_b = np.mean(b)

mu_a, mu_b

(5.0, 4.0)

In [3]:
xa = a - mu_a
xb = b - mu_b

print(xa)
print(xb)

[-3. -1.  1.  3.]
[-3. -1.  1.  3.]


In [4]:
np.dot(xa, xb)

20.0

In [5]:
np.dot(xa, xa)

20.0

In [6]:
import scipy.stats as sts
# return two values: The correlation coefficient and The p-value
sts.pearsonr(a, b)    # Pearson's r

(1.0, 0.0)

In [7]:
np.corrcoef(a, b)

array([[1., 1.],
       [1., 1.]])

In [8]:
np.dot(xa, xb)/(np.sqrt(np.dot(xa, xa)) * np.sqrt(np.dot(xb, xb)))

0.9999999999999998

In [9]:
def corr(a, b):
    xa = a - np.mean(a)
    xb = b - np.mean(b)
    
    norma = np.sqrt(np.dot(xa, xa))
    normb = np.sqrt(np.dot(xb, xb))
    
    return np.dot(xa, xb)/(norma * normb)

In [10]:
corr(a, b)

0.9999999999999998

In [11]:
from scipy import spatial

1 - spatial.distance.cosine(xa, xb)

1.0

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(xa.reshape(1, -1), xb.reshape(1, -1))

array([[1.]])

# Deneme

In [51]:
a = np.array([2,4,6,8])
b = np.array([9,3,1,0])

xa = a - mu_a
xb = b - mu_b

In [52]:
from numpy.linalg import norm

# compute cosine similarity
cosine = np.dot(xa,xb)/(norm(xa)*norm(xb))
print("Cosine Similarity:", cosine)

Cosine Similarity: -0.9080252220734667


In [53]:
corr(a, b)

-0.9287432920695055

In [54]:
corr(xa, xb)

-0.9287432920695055

In [55]:
sts.pearsonr(a, b)[0]

-0.9287432920695053

In [56]:
#1 - spatial.distance.cosine(xa, xb)

In [57]:
#cosine_similarity(xa.reshape(1, -1), xb.reshape(1, -1))

In [61]:
a = np.array([2,4,6,8])
b = np.array([9,3,1,0])

xa = a - mu_a
xb = b - mu_b

In [62]:
from numpy.linalg import norm

# compute cosine similarity
cosine = np.dot(xa,xb)/(norm(xa)*norm(xb))
print("Cosine Similarity:", cosine)

Cosine Similarity: -0.9080252220734667


In [63]:
corr(a, b)

-0.9287432920695055

In [64]:
sts.pearsonr(xa, xb)[0]

-0.9287432920695053

In [65]:
norm(xa)

4.47213595499958

In [66]:
norma = np.sqrt(np.dot(xa, xa))
norma

4.47213595499958

In [67]:
norm(xb)

7.14142842854285

In [68]:
normb = np.sqrt(np.dot(xb, xb))
normb

7.14142842854285

In [69]:
xa = a - np.mean(a)
xb = b - np.mean(b)

norma = np.sqrt(np.dot(xa, xa))
normb = np.sqrt(np.dot(xb, xb))

np.dot(xa, xb)/(norma * normb)

-0.9287432920695055

In [70]:
np.dot(xa,xb)/(norm(xa)*norm(xb))

-0.9287432920695055

In [71]:
from numpy.linalg import norm

# compute cosine similarity
cosine = np.dot(xa,xb)/(norm(xa)*norm(xb))
print("Cosine Similarity:", cosine)

Cosine Similarity: -0.9287432920695055
